apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marquez.fullname" . }}
  labels:
    {{- include "marquez.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "marquez.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Force pod restart on config changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-db-creds: {{ .Values.vault.secretPath | quote }}
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{`{{- with secret "`}}{{ .Values.vault.secretPath }}{{`" -}}`}}
          export DATABASE_USER="{{`{{ .Data.username }}`}}"
          export DATABASE_PASSWORD="{{`{{ .Data.password }}`}}"
          {{`{{- end -}}`}}
        vault.hashicorp.com/auth-path: {{ .Values.vault.authPath | quote }}
        vault.hashicorp.com/agent-image: "{{ .Values.vault.agentImage.repository }}:{{ .Values.vault.agentImage.tag }}"
        {{- end }}
      labels:
        {{- include "marquez.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.vault.enabled }}
      serviceAccountName: {{ .Values.vault.serviceAccount }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_URL
              value: "http://{{ .Values.api.host }}:{{ .Values.api.port }}"
            {{- if .Values.vault.enabled }}
            # Database connection will be set by sourcing the Vault credentials
            - name: DATABASE_HOST
              value: {{ .Values.database.host | quote }}
            - name: DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.database.name | quote }}
            {{- end }}
          {{- if .Values.vault.enabled }}
          command:
            - /bin/sh
            - -c
            - |
              # Source database credentials from Vault
              . {{ .Values.database.credentialsPath }}
              # Start the application
              exec npm start
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            {{- if .Values.vault.enabled }}
            - name: vault-secrets
              mountPath: {{ .Values.database.credentialsPath | dir }}
              readOnly: true
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "marquez.fullname" . }}-config
        {{- if .Values.vault.enabled }}
        - name: vault-secrets
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}