{{- if .Values.vault.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "marquez.fullname" . }}-vault-auth
  labels:
    {{- include "marquez.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts", "serviceaccounts/token"]
    verbs: ["get", "list", "create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "marquez.fullname" . }}-vault-auth
  labels:
    {{- include "marquez.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "marquez.fullname" . }}-vault-auth
subjects:
  - kind: ServiceAccount
    name: {{ .Values.vault.serviceAccount }}
    namespace: {{ .Release.Namespace }}
{{- end }}