{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.serviceAccount }}
  labels:
    {{- include "marquez.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}